context:
  name: together
  version: "2.2.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8270f41ab29bca7d2a7931eaaa78ba7dc0fa33566fac15df591946b4ba731e77

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python >=${{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.10,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - click >=8.1.7
    - rich >=13.7.1
    - tabulate >=0.9.0
    - pillow >=10.4.0
    - types-tabulate >=0.9.0.20240106
    - tqdm >=4.67.1
    - types-tqdm >=4.67.0.20250516
    - filelock >=3.13.1
    - types-pyyaml >=6.0.12.20250915
    - tomli >=2.0.0

  run_constraints:
    - httpx-aiohttp >=0.1.9
    - aiofiles >=25.0.0
    - pyarrow >=16.1.0

tests:
  - python:
      imports:
        - together
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: The Official Python Client for Together's API
  homepage: https://github.com/togethercomputer/together-py
  repository: https://github.com/togethercomputer/together-py

extra:
  recipe-maintainers:
    - timkpaine
