context:
  name: together
  version: "2.1.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a368dad7570f0df9c0470551d4413a4990a56a1f3ad3a427afc5459362985f52

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }}
    - typer >=0.9,<0.16
    - requests >=2.31.0,<3.0.0
    - rich >=13.8.1,<15.0.0
    - tqdm >=4.66.2,<5.0.0
    - tabulate >=0.9.0,<1.0.0
    - pydantic >=2.6.3,<3.0.0
    - aiohttp >=3.9.3,<4.0.0
    - filelock >=3.13.1,<4.0.0
    - eval-type-backport >=0.1.3,<0.3.0
    - click >=8.1.7,<9.0.0
    - pillow >=11.1.0,<12.0.0
    - numpy >=1.23.5
    - black >=25.9.0,<26

  run_constraints:
    - pyarrow >=10.0.1

tests:
  - python:
      imports:
        - together
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: The Official Python Client for Together's API
  homepage: https://github.com/togethercomputer/together-python
  repository: https://github.com/togethercomputer/together-python

extra:
  recipe-maintainers:
    - timkpaine
